sudo: required
services:
  - docker
  
before_install: 
  - docker build -t tsu-dev/prod-demo -f Dockerfile.dev .

script:
  - docker run tsu-dev/prod-demo npm run test
  
deploy:
  - provider: elasticbeanstalk
  - region: "us-west-2"
  - app: "docker"
  - env: "Docker-env"
  - bucket_name: "bucket-name"
  - bucket_path: "docker"
  on:
    branch: master